### ISSUE TITLE
Perspective attribute of view element overrides view*projection matrix

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#106]
* position, orientation of view element are ignored
* transformation of group hierarchy with embedded view gets lost as well

Test case: https://github.com/stlemme/xml3d-experimental/tree/master/projections

**Comment by csvurt** [comment]
There was a bug preventing the scene from being redrawn when the value of the perspective matrix changes, this was fixed in d1f911eeaa9a1fa4ebd71e93254678bcc232b8d5. The rest seems to be working properly.

As a heads up we'll be specifying this feature further in version 5.0 and will probably rename the attribute then.
