### ISSUE TITLE
Error when style="display:none;" on configuration

### ISSUE THREAD

**Issue by l337r007** [xml3d/xml3d.js#11]
console:
```
WebGL: checkFramebufferStatus: attachment has a 0 dimension
Incomplete framebuffer: FRAMEBUFFER_INCOMPLETE_ATTACHMENT
```
Sometimes you may want to start loading everything in the background and only begin showing the scene after everything has arrived.
Current workaround is to `style="position:absolute; opacity: 0;"` so the canvas doesn't impede layout flow and is not visible, but still passes configuration.

**Comment by csvurt** [comment]
This issue seems to be resolved. Using "display: none" on the xml3d element will cause the canvas to fallback to a default size (800x600) during configuration. Querying the clientWidth or clientHeight of the xml3d or canvas elements in this state will return 0, as it does in HTML.

If "display: none" is later removed the canvas is resized to its proper size according to CSS width/height or the width/height attributes on the xml3d element.
