### ISSUE TITLE
XML3D Shaders: default uniforms 

### ISSUE THREAD

**Issue by Arsakes** [xml3d/xml3d.js#179]
Where can I find the list of uniforms defined for xml3d shaders?
Surely some of them are predefined.

To be precise: I'm looking for inversion of modelView matrix. It would be great if I could bypass computing it in shader.

**Comment by csvurt** [comment]
Hi,

these aren't documented anywhere right now, but you can look at the source code to see what's defined:

[SceneRenderPass](https://github.com/xml3d/xml3d.js/blob/master/src/renderer/webgl/render-passes/scene-pass.js)
[Phong shader](https://github.com/xml3d/xml3d.js/blob/master/src/renderer/webgl/materials/urn/phong.js)

Of course if you're writing your own RenderPass you can define any uniforms that you want, but these are the ones that get supplied to the shader during the built in scene render pass.

**Comment by Arsakes** [comment]
Great thanks, `modelViewMatrixN` is trasposition of an inverse of modelView - right?
Also have a question which is maybe slighlty out of scope, how can I check which version of shading language (opengl es) I'm using?

**Comment by csvurt** [comment]
No they're just 3x3 versions of the the matrices meant to be used with vertex normals. The renderer doesn't provide the inverse matrices, but if you need them you could define your own copy of the SceneRenderPass and add them to the ```systemUniforms``` array yourself. You'd just need to replace the ```require``` imports with calls to the global ```XML3D``` object instead, like:

```javascript
var BaseRenderPass = XML3D.webgl.BaseRenderPass;
var Options = XML3D.options;
var mat4 = XML3D.math.mat4;
```

Then in your RenderTree instead of creating an instance of the internal SceneRenderPass you create your own:

```javascript
var scenePass = new MySceneRenderPass(renderInterface, output, opt);
```

About the version, it should always be the same since WebGL 1.0 is the only supported API right now. It's basically OpenGL ES 2.0 and GLSL ES 1.0. But you can check this by creating a webgl context and reading out the version constants:

```javascript
var canvas = document.createElement("canvas");
var gl = canvas.getContext("webgl");
gl.VERSION
gl.SHADING_LANGUAGE_VERSION
```

**Comment by csvurt** [comment]
FYI, just remembered there are a few more uniforms set in the [forward render pass](https://github.com/xml3d/xml3d.js/blob/master/src/renderer/webgl/render-passes/forward.js) which is what kicks off the scene render passes. So these should be available in your shader too:

```javascript
systemUniforms["viewMatrix"] = c_worldToViewMatrix;
systemUniforms["viewInverseMatrix"] = c_viewToWorldMatrix;
systemUniforms["projectionMatrix"] = c_projectionMatrix;
systemUniforms["cameraPosition"] = scene.getActiveView().getWorldSpacePosition();
systemUniforms["coords"] = [target.width, target.height, 1];
```

**Comment by Arsakes** [comment]
Great! _viewInverseMatrix_ is precisely what I've needed!
