### ISSUE TITLE
Rotating around center of the model

### ISSUE THREAD

**Issue by dasha-5555-5** [xml3d/xml3d.js#181]
Hi! My mesh is in ctm format. I can't set examine point of my mesh and I don't know how to count the center of mass my mesh and rotate mesh around it's center. I already have testing many variants such as  "var camera = new XML3D.StandardCamera(viewElem, {mode:"examine", useKeys: true})", "camera.examine(mesh);", also I followed by this examples: http://xml3d.github.io/xml3d-examples/examples/candle/candle.html, http://xml3d.github.io/xml3d.tools.js/cameracontrollers.xhtml, but in my case my model rotating in depends on camera view. Can anyone help me?

**Comment by csvurt** [comment]
Hi,

there are a few things we should check. First make sure there are no other transformations affecting the ```<view>``` element that you're using, besides the one that the StandardCamera creates (which will be named something like ```Generated_Camera_Transform_0```). Best thing would be to put a view element right under the xml3d element and set it as the active view:

```html
<xml3d view="#cameraView">
   <view id="cameraView"></view>
   ...
</xml3d>
``` 

Next, if you're using ```camera.examine()``` make sure the object that you want to examine is finished loading before you call that function, otherwise it could break the camera. I'll add a check for this to the next release. Best thing would be to use the load event on the mesh that you want to examine:

```html
<mesh onload="initializeMyCamera(event)" src="myMesh.ctm"></mesh>
```

Or use the onload event on the ```<xml3d>``` element which will fire when all the meshes and materials in the scene are done loading.

If all that checks out then see if you can link the scene with the CTM model here and I'll take a look at it.

**Comment by dasha-5555-5** [comment]
Thanks! It really works!!

**Comment by csvurt** [comment]
Cool, glad you got it working!
