### ISSUE TITLE
getElementByRay(): computation of hit point wrong when big triangles are present

### ISSUE THREAD

**Issue by uykusuz** [xml3d/xml3d.js#60]
I have a 1x1 rectangle with a normal of (0,0,1). I rotate this rectangle so it has a normal of (0,1,0). I translate it along the y-axis by -1. Now I shoot ray and get the following result: 
```
ray: [ pos: 0.000 2.000 0.000; dir: 0.000 -1.000 0.000]
hit point : 0.004 -1.000 -0.004
```

If I scale the rectangle by a factor of 100 I get the following result: 

```
ray: [ pos: 0.000 2.000 0.000; dir: 0.000 -1.000 0.000]
hit point : 0.392 -1.000 -0.392
```
That's way more than a simple rounding error.

**Comment by csvurt** [comment]
So it seems like this is caused by WebGL color buffer limitations. To find the picked position we use a fragment shader to encode the x,y,z positions of the fragments relative to the picked object's bounding box in world space. In other words, the rgb channels each contain percentage values that are later multiplied with the xyz axes of the bounding box to reconstruct a floating point position.

At 8 bits per channel we're obviously stuck with decreasing accuracy as bounding boxes grow larger.

The OES_texture_float extension is in [a weird place right now](https://www.khronos.org/webgl/public-mailing-list/archives/1407/msg00051.html) making it difficult to use floating point buffers reliably.

We could add a second, slower high precision getter for the picked position but this would be a low priority enhancement. For example we could leverage 3 rendering passes to encode the xyz positions as 32 bit floating point values across the rgba buffers.

**Comment by csvurt** [comment]
I've opened a new enhancement issue for this use case (#101). The original lower precision implementation will stay unchanged because it seems like a good compromise between speed and accuracy for most use cases.
