### ISSUE TITLE
WheelEvent turns into MouseEvent in Chrome

### ISSUE THREAD

**Issue by simpae** [xml3d/xml3d.js#73]
Usually when using an eventhandler for "mousewheel" the event is of type WheelEvent. However xml3d generates a MouseEvent which is missing information about the wheel delta. As far as I know this only applies to Chrome. Firefox uses a DOMMouseScroll Event instead.

````js
var xml3dElem = document.querySelector('xml3d');
xml3dElem.addEventListener('mousewheel', wheelEventHandler);

function wheelEventHandler(event) {
    console.log(event);     // will output event of type MouseEvent, not WheelEvent as expected
}
````

**Comment by csvurt** [comment]
This has been fixed in 4ea9ac73b40a70b629213ba1068c45af0dd5af5b which will be part of the 4.9 release. 

XML3D now supports the "wheel" event type which will return a WheelEvent object (with the delta fields) instead of a MouseEvent. 

DOMMouseScroll is not a standard event and remains unsupported, but modern Firefox supports the "wheel" events anyway.
