### ISSUE TITLE
Invalid texture data with deactivated mipmaps

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#88]
Using the texture filter combination (linear/linear)
```html
<texture name="arvideo" filterMin="linear" filterMag="linear">
    <video autoplay="true" id="inputvideo" src="resources/my-video.mp4"></video>
</texture>
```
as shader input in conjunction with the usage of an Xflow operator results in an
> Error: WebGL: texImage2D: invalid typed array type for given texture data type

Instead of directly passed the HTMLElement to WebGL, an ImageData object is retrieved from an internal canvas to fetch a frame of the video stream. This call returns an Uint8ClampedArray, which in turn is not valid as argument to be given to texImage2D (requires Uint8Array).

**Comment by csvurt** [comment]
Xflow uses Uint8ClampedArrays when web workers are involved, which is the right way to go about it I think. However WebGL doesn't accept these as data sources for  tex2D, the [suggested fix](https://www.khronos.org/webgl/public-mailing-list/archives/1307/msg00054.html) for this is to simply create a Uint8Array view on the underlying ArrayBuffer.

The above commit should cover all cases where a clamped array is used because the conversion is applied just before the data is sent to the gl context. With that I'll close this issue, if you still have this problem with the 4.9 release go ahead and reopen it.
