### ISSUE TITLE
Feature: Set mesh type using Xflow

### ISSUE THREAD

**Issue by stlemme** [xml3d/xml3d.js#93]
When generating or modifying mesh data with Xflow, this usually relies on a dedicated assumption about the arrangement of the index buffer (i.e. triangles, tristrips, etc.). Thus, the possible values of the type-attribute are limited to "meaningful" values and need to be maintained manually.

It might make sense to set the "type" of a mesh together with the index buffer by an operator that generates the respective index buffer (i.e. during polygon tesselation/extrusion, stripification of meshes, etc.).

Probably, an Xflow type for strings need to be introduced beforehand.

**Comment by csvurt** [comment]
I've just merged this feature into develop with commit 44a85ab3250f6008b36c9fcd1771675b01c7f162. We now have a new ```<string>``` element that can be used as input for Xflow. Mesh type can then be set like so for example:

```html
<data id="meshTypeCompute" compute="type = xflow.selectString(selector, value1, value2)">
      <string name="value1">triangles</string>
      <string name="value2">lines</string>
      <int name="selector">0</int>
</data>
<mesh src="#meshdata" type="#meshTypeCompute"></mesh>
```

As typical for Xflow you can also reference an external data element, as long as the '#' character appears somewhere in the attribute value (otherwise the value is treated as a 'simple' case ie. the mesh type is just given directly). 

Besides type for meshes and assetmeshes we've also allowed setting the ```wrap``` and ```filter``` attributes of the ```texture``` element in this manner.
